"use client";

import { useCallback, useSyncExternalStore } from "react";

/*
 * Sound, synthesised.
 *
 * Every tone on this site is generated by the Web Audio API at runtime — there
 * is not one audio file in the bundle. That's a deliberate trade:
 *
 *  - Zero bytes. A two-minute ambient loop is 2-4 MB even at a mean bitrate,
 *    which is more than the entire rest of the site put together.
 *  - Zero licensing. No stock-music attribution, no royalty question, nothing
 *    to get wrong for a business that has to ship legally clean.
 *  - It never loops audibly. The pad is four detuned voices whose amplitudes
 *    are driven by LFOs at mutually irrational-ish rates, so the texture keeps
 *    recombining instead of repeating on a seam.
 *
 * Nothing here is constructed until the visitor turns sound on. An AudioContext
 * created at import time would be suspended by autoplay policy anyway, and it
 * would cost main-thread work on every page load for a feature most people
 * never enable.
 */

const STORAGE_KEY = "nla-sound";

type Engine = {
  ctx: AudioContext;
  master: GainNode;
  sfx: GainNode;
  /** Stop the pad and release the graph. */
  teardown: () => void;
};

let engine: Engine | null = null;
let lastHover = 0;

function build(): Engine | null {
  const Ctor =
    window.AudioContext ??
    (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
  if (!Ctor) return null;

  const ctx = new Ctor();

  const master = ctx.createGain();
  master.gain.value = 0;
  master.connect(ctx.destination);

  /*
   * Space, without a convolver. A ConvolverNode with a 2s impulse is the
   * obvious way to get this and costs real CPU per sample; two prime-ish
   * delays with damped feedback give the same sense of a large room for
   * almost nothing, which matters because this runs the whole time the tab
   * is open.
   */
  const wet = ctx.createGain();
  wet.gain.value = 0.42;
  wet.connect(master);

  const damp = ctx.createBiquadFilter();
  damp.type = "lowpass";
  damp.frequency.value = 1600;
  damp.connect(wet);

  for (const time of [0.317, 0.473]) {
    const delay = ctx.createDelay(1);
    delay.delayTime.value = time;
    const fb = ctx.createGain();
    fb.gain.value = 0.44;
    delay.connect(fb);
    fb.connect(damp);
    damp.connect(delay);
    delay.connect(wet);
  }

  // Everything voiced goes through here so the pad sits behind the reverb.
  const bus = ctx.createGain();
  bus.gain.value = 0.5;
  bus.connect(master);
  bus.connect(damp);

  const sfx = ctx.createGain();
  sfx.gain.value = 0.9;
  sfx.connect(master);
  sfx.connect(damp);

  /* A minor-ninth voicing on A — open enough not to declare a mood, low
     enough to stay under speech and UI sound. */
  const voices: [freq: number, lfo: number, level: number][] = [
    [55, 0.037, 0.5], // A1 — body
    [110, 0.041, 0.34], // A2
    [164.81, 0.029, 0.26], // E3
    [246.94, 0.023, 0.16], // B3 — the ninth
    [329.63, 0.019, 0.1], // E4 — air
  ];

  const tone = ctx.createBiquadFilter();
  tone.type = "lowpass";
  tone.frequency.value = 900;
  tone.Q.value = 0.6;
  tone.connect(bus);

  // Slow filter sweep: the pad opens and closes over ~50s, which is what keeps
  // it from reading as a held chord.
  const sweep = ctx.createOscillator();
  sweep.frequency.value = 0.02;
  const sweepDepth = ctx.createGain();
  sweepDepth.gain.value = 420;
  sweep.connect(sweepDepth);
  sweepDepth.connect(tone.frequency);
  sweep.start();

  for (const [freq, rate, level] of voices) {
    // Two oscillators a few cents apart per voice — the beating between them
    // is the whole reason a synth pad sounds wide instead of thin.
    for (const detune of [-6, 6]) {
      const osc = ctx.createOscillator();
      osc.type = "sine";
      osc.frequency.value = freq;
      osc.detune.value = detune;

      const amp = ctx.createGain();
      amp.gain.value = level * 0.5;

      const lfo = ctx.createOscillator();
      lfo.frequency.value = rate;
      const lfoDepth = ctx.createGain();
      lfoDepth.gain.value = level * 0.45;
      lfo.connect(lfoDepth);
      lfoDepth.connect(amp.gain);
      lfo.start();

      osc.connect(amp);
      amp.connect(tone);
      osc.start();
    }
  }

  return {
    ctx,
    master,
    sfx,
    teardown: () => {
      const now = ctx.currentTime;
      master.gain.cancelScheduledValues(now);
      master.gain.setValueAtTime(master.gain.value, now);
      master.gain.linearRampToValueAtTime(0, now + 0.6);
      window.setTimeout(() => void ctx.close(), 800);
    },
  };
}

/** Fade the pad in over a few seconds — a hard start is a jump scare. */
function fadeIn(e: Engine) {
  const now = e.ctx.currentTime;
  e.master.gain.cancelScheduledValues(now);
  e.master.gain.setValueAtTime(e.master.gain.value, now);
  e.master.gain.linearRampToValueAtTime(0.12, now + 3.5);
}

async function start() {
  if (!engine) engine = build();
  if (!engine) return;
  // Chrome starts the context suspended until a gesture; the toggle click is
  // that gesture, so resume happens here rather than on load.
  if (engine.ctx.state === "suspended") await engine.ctx.resume();
  fadeIn(engine);
}

function stop() {
  engine?.teardown();
  engine = null;
}

/* ------------------------------------------------------------------ *
 * One-shots
 * ------------------------------------------------------------------ */

/**
 * Hover: a short two-partial blip, high and quiet. Rate-limited, because
 * dragging the pointer across a nav would otherwise fire five of these in
 * 200ms and sound like a fault.
 */
export function playHover() {
  if (!engine || engine.ctx.state !== "running") return;
  const now = engine.ctx.currentTime;
  if (now - lastHover < 0.07) return;
  lastHover = now;

  const { ctx, sfx } = engine;
  const gain = ctx.createGain();
  gain.gain.setValueAtTime(0.0001, now);
  gain.gain.exponentialRampToValueAtTime(0.055, now + 0.004);
  gain.gain.exponentialRampToValueAtTime(0.0001, now + 0.14);
  gain.connect(sfx);

  for (const [freq, level] of [
    [1864, 1],
    [2794, 0.4],
  ]) {
    const osc = ctx.createOscillator();
    osc.type = "sine";
    osc.frequency.setValueAtTime(freq, now);
    // A slight downward glide is what makes it read as "instrument panel"
    // rather than "notification".
    osc.frequency.exponentialRampToValueAtTime(freq * 0.94, now + 0.14);
    const g = ctx.createGain();
    g.gain.value = level;
    osc.connect(g);
    g.connect(gain);
    osc.start(now);
    osc.stop(now + 0.16);
  }
}

/**
 * Click: a filtered noise transient over a short low body — the shape of a
 * switch closing, not a beep.
 */
export function playClick() {
  if (!engine || engine.ctx.state !== "running") return;
  const { ctx, sfx } = engine;
  const now = ctx.currentTime;

  const frames = Math.floor(ctx.sampleRate * 0.03);
  const buffer = ctx.createBuffer(1, frames, ctx.sampleRate);
  const data = buffer.getChannelData(0);
  for (let i = 0; i < frames; i++) {
    // Linear decay across the burst; anything longer starts to hiss.
    data[i] = (Math.random() * 2 - 1) * (1 - i / frames);
  }

  const noise = ctx.createBufferSource();
  noise.buffer = buffer;
  const band = ctx.createBiquadFilter();
  band.type = "bandpass";
  band.frequency.value = 2400;
  band.Q.value = 1.4;
  const noiseGain = ctx.createGain();
  noiseGain.gain.setValueAtTime(0.09, now);
  noiseGain.gain.exponentialRampToValueAtTime(0.0001, now + 0.05);
  noise.connect(band);
  band.connect(noiseGain);
  noiseGain.connect(sfx);
  noise.start(now);

  const body = ctx.createOscillator();
  body.type = "triangle";
  body.frequency.setValueAtTime(320, now);
  body.frequency.exponentialRampToValueAtTime(140, now + 0.09);
  const bodyGain = ctx.createGain();
  bodyGain.gain.setValueAtTime(0.0001, now);
  bodyGain.gain.exponentialRampToValueAtTime(0.07, now + 0.005);
  bodyGain.gain.exponentialRampToValueAtTime(0.0001, now + 0.12);
  body.connect(bodyGain);
  bodyGain.connect(sfx);
  body.start(now);
  body.stop(now + 0.14);
}

/* ------------------------------------------------------------------ *
 * Preference store
 * ------------------------------------------------------------------ */

const listeners = new Set<() => void>();
/** null until first read — the snapshot caches it, it isn't re-read per call. */
let enabled: boolean | null = null;

function emit() {
  for (const l of listeners) l();
}

function subscribe(onChange: () => void) {
  listeners.add(onChange);
  return () => {
    listeners.delete(onChange);
  };
}

function getSnapshot() {
  if (enabled === null) {
    try {
      enabled = window.localStorage.getItem(STORAGE_KEY) === "on";
    } catch {
      enabled = false;
    }
  }
  return enabled;
}

/**
 * For a returning visitor whose preference is already "on": autoplay policy
 * still won't let a context run before a gesture, so the pad waits for the
 * first click or keypress rather than starting on load. Silently a no-op when
 * sound is off or already running.
 */
export function resumeIfEnabled() {
  if (getSnapshot()) void start();
}

/**
 * `on` plus a toggle. Sound is off on first visit and stays off until asked
 * for — autoplaying audio at someone is the most hostile thing a site can do,
 * and browsers block it anyway.
 */
export function useSound() {
  const on = useSyncExternalStore(subscribe, getSnapshot, () => false);

  const toggle = useCallback(() => {
    enabled = !getSnapshot();
    try {
      window.localStorage.setItem(STORAGE_KEY, enabled ? "on" : "off");
    } catch {
      /* private mode — the session still works, the choice just won't stick */
    }
    if (enabled) void start();
    else stop();
    emit();
  }, []);

  return { on, toggle };
}
